version: "3.9"
services: 
    laravel_composer:
        image: composer
        volumes:
          - ./backend:/work/backend
        working_dir: /work/backend

    laravel_app:
        build: ./infra/app
        ports:
            - 9000:9000
        volumes: 
            - ./backend:/var/www/html
        working_dir: /var/www/html

    laravel_web:
        image: nginx:stable-alpine
        ports:
            -  8888:80
        volumes:
            -  ./backend:/var/www/html
            -  ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -  laravel_app
            -  laravel_db

    laravel_db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        ports: 
            - 3306:3306
        volumes: 
            - laravel-db-data:/var/lib/mysql
    
    laravel_adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes: 
    laravel-db-data:
